# Generated by Django 4.2.10 on 2024-02-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=122)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('activity_level', models.CharField(blank=True, max_length=50)),
                ('exercise_frequency', models.CharField(blank=True, max_length=50)),
                ('vegetarian', models.CharField(blank=True, max_length=50, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('cholesterol_level', models.CharField(blank=True, max_length=20)),
                ('sleep_duration', models.FloatField(blank=True, null=True)),
                ('sleep_quality', models.CharField(blank=True, max_length=50)),
                ('smoking_status', models.CharField(blank=True, max_length=50)),
                ('alcohol_consumption', models.CharField(blank=True, max_length=50)),
                ('stress_level', models.CharField(blank=True, max_length=50)),
                ('mental_health_status', models.CharField(blank=True, max_length=50)),
                ('health_goals', models.TextField(blank=True)),
            ],
        ),
    ]
